name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    environment: production
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Test S3 Write (FIXED)
        run: |
          echo "test" > test.txt
      
          aws s3api put-object \
            --bucket terraform-state \
            --key test.txt \
            --body test.txt \
            --endpoint-url https://sg-sin-1.linodeobjects.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # ✅ DEBUG LIST
      - name: Debug S3 Access
        run: |
          aws s3 ls --endpoint-url https://sg-sin-1.linodeobjects.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform -chdir=terraform plan
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
